import { type NextPage } from "next";
import Head from "next/head";
import BarChart from "~/components/BarChart";
import DashboardTopBars from "~/components/DashboardTopBars";
import DoughnutChart from "~/components/DoughnutChart";
import RecentTransactions from "~/components/RecentTransactions";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: total } = api.transaction.getTotalByCategory.useQuery();
  const { data: spendingStats, isLoading: statsLoading } =
    api.transaction.getSpendingStats.useQuery();
  const { data: recentTransactions, isLoading: transactionsLoading } =
    api.transaction.getRecentTransactions.useQuery();
  const { data: transactionsByMonth } =
    api.transaction.getAmountSpentPerMonth.useQuery();

  const categoryNames = total ? total.map((t) => t.name) : [];
  const totalAmounts = total ? total.map((t) => t.total) : [];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  mt-20 w-full">
        <DashboardTopBars
          averageMontlySpending={spendingStats?.averageMonthlySpending}
          thisMonthSpending={spendingStats?.thisMonthSpending}
          lastSevenSpending={spendingStats?.lastSevenSpending}
          isLoading={statsLoading}
        />
        <div className="grid grid-cols-1 gap-4 p-4 lg:grid-cols-3">
          <DoughnutChart
            categoryNames={categoryNames}
            totalAmounts={totalAmounts}
          />
          <RecentTransactions
            transactions={recentTransactions}
            isLoading={transactionsLoading}
          />
        </div>
        <div className="p-4">
          <BarChart amountsPerMonth={transactionsByMonth} />
        </div>
      </main>
    </>
  );
};

export default Home;
