import { type NextPage } from "next";
import Head from "next/head";
import DashboardTopBars from "~/components/DashboardTopBars";
import PieChart from "~/components/PieChart";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: total } = api.transaction.getTotalByCategory.useQuery();
  const { data: spendingStats } = api.transaction.getSpendingStats.useQuery();

  const categoryNames = total ? total.map((t) => t.name) : [];
  const totalAmounts = total ? total.map((t) => t.total) : [];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-2 mx-auto mt-20 w-full">
        <DashboardTopBars
          averageMontlySpending={spendingStats?.averageMonthlySpending}
          thisMonthSpending={spendingStats?.thisMonthSpending}
          lastSevenSpending={spendingStats?.lastSevenSpending}
        />
        <div className="grid grid-cols-1 gap-4 p-4  lg:grid-cols-3">
          <PieChart categoryNames={categoryNames} totalAmounts={totalAmounts} />
        </div>
      </main>
    </>
  );
};

export default Home;
